import sys
_USE_PYSIDE = "PySide6" in sys.modules or ("PyQt6" not in sys.modules and ("PySide6" in sys.modules or True))

try:
    if _USE_PYSIDE:
        from PySide6.QtCore import (
            QEasingCurve,
            QEvent,
            QObject,
            QProcess,
            QProcessEnvironment,
            QPropertyAnimation,
            QSettings,
            QSize,
            Qt,
            QTimer,
            QUrl,
            Signal as pyqtSignal,
        )
        from PySide6.QtGui import (
            QColor,
            QDesktopServices,
            QFont,
            QGuiApplication,
            QIcon,
            QPalette,
            QPixmap,
            QSyntaxHighlighter,
            QTextCharFormat,
            QTextDocument,
        )
        from PySide6.QtWidgets import (
            QAbstractSpinBox,
            QApplication,
            QCheckBox,
            QComboBox,
            QDoubleSpinBox,
            QFileDialog,
            QFormLayout,
            QFrame,
            QGridLayout,
            QGroupBox,
            QHBoxLayout,
            QInputDialog,
            QLabel,
            QLineEdit,
            QListWidget,
            QListWidgetItem,
            QMainWindow,
            QMessageBox,
            QPlainTextEdit,
            QProgressBar,
            QPushButton,
            QScrollArea,
            QSizePolicy,
            QSpinBox,
            QSplitter,
            QStackedWidget,
            QSystemTrayIcon,
            QTabWidget,
            QToolButton,
            QVBoxLayout,
            QWidget,
        )
    else:
        raise ImportError
except ImportError:
    from PyQt6.QtCore import (
        QEasingCurve,
        QEvent,
        QObject,
        QProcess,
        QProcessEnvironment,
        QPropertyAnimation,
        QSettings,
        QSize,
        Qt,
        QTimer,
        QUrl,
        pyqtSignal,
    )
    from PyQt6.QtGui import (
        QColor,
        QDesktopServices,
        QFont,
        QGuiApplication,
        QIcon,
        QPalette,
        QPixmap,
        QSyntaxHighlighter,
        QTextCharFormat,
        QTextDocument,
    )
    from PyQt6.QtWidgets import (
        QAbstractSpinBox,
        QApplication,
        QCheckBox,
        QComboBox,
        QDoubleSpinBox,
        QFileDialog,
        QFormLayout,
        QFrame,
        QGridLayout,
        QGroupBox,
        QHBoxLayout,
        QInputDialog,
        QLabel,
        QLineEdit,
        QListWidget,
        QListWidgetItem,
        QMainWindow,
        QMessageBox,
        QPlainTextEdit,
        QProgressBar,
        QPushButton,
        QScrollArea,
        QSizePolicy,
        QSpinBox,
        QSplitter,
        QStackedWidget,
        QSystemTrayIcon,
        QTabWidget,
        QToolButton,
        QVBoxLayout,
        QWidget,
    )


class NoScrollComboBox(QComboBox):
    def wheelEvent(self, e):
        e.ignore()
